# Generated by Django 3.2 on 2021-08-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20210805_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d', verbose_name='Fotoğraf Ekleyin'),
        ),
    ]
