# Generated by Django 3.2.5 on 2021-08-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, null=True, upload_to=True, verbose_name='Fotoğraf Ekleyin'),
        ),
    ]
